version: '2'
services:
  usuarios:
    build: ./usuarios
    ports:
      - "3001:3001"
    links:
      - db

  productos:
    build: ./productos
    ports:
      - "3002:3002"
    links:
      - db

  ordenes:
    build: ./ordenes
    ports:
      - "3003:3003"
    links:
      - db
      - usuarios
      - productos

  microweb:
    build: ./microweb
    ports:
      - "1080:80"
    links:
      - usuarios
      - productos
      - ordenes
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "32000:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d:ro
volumes:
  db_data: