version: '3'
services:

  microweb:   
    image: vamphook972/microweb_tienda:latest
    ports:
      - "8181:80" 
    depends_on:
      - usuarios
      - productos
      - ordenes

  usuarios:
    image: vamphook972/usuarios_tienda:latest
    ports:
      - "3001:3001"
    depends_on:
      - db_usuarios

  db_usuarios:
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=usuarios_db
    volumes:
      - ./usuarios/db:/var/lib/mysql

  productos:
    image: vamphook972/productos_tienda:latest
    ports:
      - "3002:3002"
    depends_on:
      - db_productos

  db_productos:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=productos_db
    volumes:
      - ./productos/db:/var/lib/mysql
  ordenes:
    image: vamphook972/ordenes_tienda:latest
    ports:
      - "3003:3003"
    depends_on:
      - db_ordenes
      - usuarios
      - productos
  db_ordenes:
    image: mysql:8.0
    ports:
      - "3308:3308"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=ordenes_db
    volumes:
      - ./ordenes/db:/var/lib/mysql