from node

expose 3001

workdir /usuarios

copy controllers /usuarios/controllers
copy models /usuarios/models
copy index.js /usuarios

run npm init --yes
run npm install express morgan mysql mysql2 axios

cmd node index.js