From node 

Expose 3003

workdir /ordenes

Copy controllers /ordenes/controllers
Copy models /ordenes/models
copy index.js /ordenes

run npm init --yes
run npm install express morgan mysql mysql2 axios 

cmd node index.js 

