from node 

expose 3002

workdir /productos

copy controllers /productos/controllers
copy models /productos/models
copy index.js /productos

run npm init --yes
run npm install express morgan mysql mysql2 axios

cmd node index.js
